/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCamerasRouteImport } from './routes/_authenticated/cameras'
import { Route as AuthenticatedCameraEventsIndexRouteImport } from './routes/_authenticated/camera-events.index'
import { Route as ApiPushVapidPublicKeyRouteImport } from './routes/api/push/vapid-public-key'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiPushTestRouteImport } from './routes/api/push/test'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushPreferencesRouteImport } from './routes/api/push/preferences'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as AuthenticatedCameraEventsIdRouteImport } from './routes/_authenticated/camera-events.$id'
import { Route as ApiEventsIdThumbnailRouteImport } from './routes/api/events/$id/thumbnail'
import { Route as ApiEventsIdSnapshotRouteImport } from './routes/api/events/$id/snapshot'
import { Route as ApiEventsIdClipRouteImport } from './routes/api/events/$id/clip'
import { Route as ApiCamerasNameLatestRouteImport } from './routes/api/cameras/$name/latest'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCamerasRoute = AuthenticatedCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCameraEventsIndexRoute =
  AuthenticatedCameraEventsIndexRouteImport.update({
    id: '/camera-events/',
    path: '/camera-events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPushVapidPublicKeyRoute = ApiPushVapidPublicKeyRouteImport.update({
  id: '/api/push/vapid-public-key',
  path: '/api/push/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushPreferencesRoute = ApiPushPreferencesRouteImport.update({
  id: '/api/push/preferences',
  path: '/api/push/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCameraEventsIdRoute =
  AuthenticatedCameraEventsIdRouteImport.update({
    id: '/camera-events/$id',
    path: '/camera-events/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiEventsIdThumbnailRoute = ApiEventsIdThumbnailRouteImport.update({
  id: '/api/events/$id/thumbnail',
  path: '/api/events/$id/thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdSnapshotRoute = ApiEventsIdSnapshotRouteImport.update({
  id: '/api/events/$id/snapshot',
  path: '/api/events/$id/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdClipRoute = ApiEventsIdClipRouteImport.update({
  id: '/api/events/$id/clip',
  path: '/api/events/$id/clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCamerasNameLatestRoute = ApiCamerasNameLatestRouteImport.update({
  id: '/api/cameras/$name/latest',
  path: '/api/cameras/$name/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/camera-events/$id': typeof AuthenticatedCameraEventsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/camera-events/': typeof AuthenticatedCameraEventsIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/cameras/$name/latest': typeof ApiCamerasNameLatestRoute
  '/api/events/$id/clip': typeof ApiEventsIdClipRoute
  '/api/events/$id/snapshot': typeof ApiEventsIdSnapshotRoute
  '/api/events/$id/thumbnail': typeof ApiEventsIdThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/camera-events/$id': typeof AuthenticatedCameraEventsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/camera-events': typeof AuthenticatedCameraEventsIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/cameras/$name/latest': typeof ApiCamerasNameLatestRoute
  '/api/events/$id/clip': typeof ApiEventsIdClipRoute
  '/api/events/$id/snapshot': typeof ApiEventsIdSnapshotRoute
  '/api/events/$id/thumbnail': typeof ApiEventsIdThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/cameras': typeof AuthenticatedCamerasRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/camera-events/$id': typeof AuthenticatedCameraEventsIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/push/preferences': typeof ApiPushPreferencesRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/_authenticated/camera-events/': typeof AuthenticatedCameraEventsIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/cameras/$name/latest': typeof ApiCamerasNameLatestRoute
  '/api/events/$id/clip': typeof ApiEventsIdClipRoute
  '/api/events/$id/snapshot': typeof ApiEventsIdSnapshotRoute
  '/api/events/$id/thumbnail': typeof ApiEventsIdThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cameras'
    | '/settings'
    | '/camera-events/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/push/preferences'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-public-key'
    | '/camera-events/'
    | '/api/auth/google/callback'
    | '/api/cameras/$name/latest'
    | '/api/events/$id/clip'
    | '/api/events/$id/snapshot'
    | '/api/events/$id/thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cameras'
    | '/settings'
    | '/camera-events/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/push/preferences'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-public-key'
    | '/camera-events'
    | '/api/auth/google/callback'
    | '/api/cameras/$name/latest'
    | '/api/events/$id/clip'
    | '/api/events/$id/snapshot'
    | '/api/events/$id/thumbnail'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/cameras'
    | '/_authenticated/settings'
    | '/_authenticated/camera-events/$id'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/push/preferences'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-public-key'
    | '/_authenticated/camera-events/'
    | '/api/auth/google/callback'
    | '/api/cameras/$name/latest'
    | '/api/events/$id/clip'
    | '/api/events/$id/snapshot'
    | '/api/events/$id/thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiPushPreferencesRoute: typeof ApiPushPreferencesRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiPushVapidPublicKeyRoute: typeof ApiPushVapidPublicKeyRoute
  ApiCamerasNameLatestRoute: typeof ApiCamerasNameLatestRoute
  ApiEventsIdClipRoute: typeof ApiEventsIdClipRoute
  ApiEventsIdSnapshotRoute: typeof ApiEventsIdSnapshotRoute
  ApiEventsIdThumbnailRoute: typeof ApiEventsIdThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cameras': {
      id: '/_authenticated/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AuthenticatedCamerasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/camera-events/': {
      id: '/_authenticated/camera-events/'
      path: '/camera-events'
      fullPath: '/camera-events/'
      preLoaderRoute: typeof AuthenticatedCameraEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/push/vapid-public-key': {
      id: '/api/push/vapid-public-key'
      path: '/api/push/vapid-public-key'
      fullPath: '/api/push/vapid-public-key'
      preLoaderRoute: typeof ApiPushVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/preferences': {
      id: '/api/push/preferences'
      path: '/api/push/preferences'
      fullPath: '/api/push/preferences'
      preLoaderRoute: typeof ApiPushPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/camera-events/$id': {
      id: '/_authenticated/camera-events/$id'
      path: '/camera-events/$id'
      fullPath: '/camera-events/$id'
      preLoaderRoute: typeof AuthenticatedCameraEventsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/events/$id/thumbnail': {
      id: '/api/events/$id/thumbnail'
      path: '/api/events/$id/thumbnail'
      fullPath: '/api/events/$id/thumbnail'
      preLoaderRoute: typeof ApiEventsIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id/snapshot': {
      id: '/api/events/$id/snapshot'
      path: '/api/events/$id/snapshot'
      fullPath: '/api/events/$id/snapshot'
      preLoaderRoute: typeof ApiEventsIdSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id/clip': {
      id: '/api/events/$id/clip'
      path: '/api/events/$id/clip'
      fullPath: '/api/events/$id/clip'
      preLoaderRoute: typeof ApiEventsIdClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cameras/$name/latest': {
      id: '/api/cameras/$name/latest'
      path: '/api/cameras/$name/latest'
      fullPath: '/api/cameras/$name/latest'
      preLoaderRoute: typeof ApiCamerasNameLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCamerasRoute: typeof AuthenticatedCamerasRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCameraEventsIdRoute: typeof AuthenticatedCameraEventsIdRoute
  AuthenticatedCameraEventsIndexRoute: typeof AuthenticatedCameraEventsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCamerasRoute: AuthenticatedCamerasRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCameraEventsIdRoute: AuthenticatedCameraEventsIdRoute,
  AuthenticatedCameraEventsIndexRoute: AuthenticatedCameraEventsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiPushPreferencesRoute: ApiPushPreferencesRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushTestRoute: ApiPushTestRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiPushVapidPublicKeyRoute: ApiPushVapidPublicKeyRoute,
  ApiCamerasNameLatestRoute: ApiCamerasNameLatestRoute,
  ApiEventsIdClipRoute: ApiEventsIdClipRoute,
  ApiEventsIdSnapshotRoute: ApiEventsIdSnapshotRoute,
  ApiEventsIdThumbnailRoute: ApiEventsIdThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
